.Dd October 30, 2006
.Dt RDS-GEN-SINK 1
.Os
.Sh NAME
.Nm rds-gen
.Nd write data from a file to an RDS socket
.Pp
.Nm rds-sink
.Nd write data from an RDS socket to a file
.Sh SYNOPSIS
.Nm rds-gen
.Bk -words
.Op Fl s Ar source_address:source_port
.Op Fl d Ar destination_address:destination_port
.Op Fl f Ar input_file
.Op Fl m Ar message_size
.Op Fl l Ar total_bytes
.Op Fl i Ar interval

.Nm rds-sink
.Bk -words
.Op Fl s Ar listen_address:listen_port
.Op Fl f Ar output_file
.Op Fl i Ar interval

.Sh DESCRIPTION
The
.Nm
and
.Nm rds-sink
utilities are used to stream data through RDS sockets.  rds-gen
reads data from a file descriptor and sends it as messages
down an RDS socket.  rds-sink receives messages from an RDS
socket and writes it to a file descriptor.

The following options are shared between rds-gen and rds-sink:
.Bl -tag -width Ds
.It Fl s Ar address:port
Binds the RDS socket to the given address and port.  rds-gen will
send messages from this address and port.  rds-sink will receive messages
sent to this address and port.
.It Fl f Ar file
rds-gen will read data from this file and rds-sink will write
data to this file.  If '-' is given as the filename then rds-gen
will use standard input and rds-sink will use standard output.
.It Fl i Ar interval_seconds
An iterative summary of the number and size of messages that are sent and
received is written to standard error at this interval.
.El
.Pp

In addition, rds-gen supports the following options:
.Bl -tag -width Ds
.It Fl d Ar address:port
Messages are sent to this destination address and port.  If this option
is specified multiple times then the messages are sent to each destination
address in a round-robin fashion.
.It Fl m Ar message_size
Specifies the size of the messages that are sent down the RDS socket.  The default
message size is 4k.  The message size must not be greater than the buffer size.
.It Fl l Ar total_bytes
Specifies the number of bytes that will be sent out the socket before rds-gen
exits.  If this is not specified and rds-gen was given a source file then it
will run until it gets EOF from the file.  If no file was given and this
option is not specified then rds-gen will send data indefinitely.
.El
.Pp

.Sh EXAMPLES
rds-gen on host src sends infinite data to rds-sink on dest who
prints out the amount of data it receives every second.
.Pp

.Dl $ rds-sink -s dest:22222 -i 1
.Dl $ rds-gen -s src:11111 -d dest:22222
.Pp

Read 100M from /dev/zero on src and write it to /dev/null on dest,
printing stats on both sides every minute.

.Dl $ rds-sink -s dest:22222 -f /dev/null -i 60
.Dl $ rds-gen -s src:11111 -f /dev/zero -d dest:22222 -i 60
.Pp

Watch rds-gen write data as fast as it can into a local black hole because
there is no bound receiving socket.

.Dl $ rds-gen -s src:11111 -d localhost:31337 -i 1
.Pp
